typography_spectrum: 0.7110840214882046
color:
  saturation: 0.6540196472778916
  brandStrength: 0.443769803037867
  rhythmicContrast: 0.7665214303415269
  brandColors:
    - '#081D6A'
    - '#D2001A'
    - '#FFDC00'
    - '#F8AC00'
    - '#172863'
  lightness: 0.07657347363419831
layout_spectrum: 0.08712571859359741
name: PAT-K
navigation:
  - name: Google Play
    url: >-
      https://play.google.com/store/music/album/Pat_Kaye_Lack_of_Budget?id=B67ojy3nariysi6qocb5iqyhh4e&hl=en
    type: external
  - name: Contact
    id: 02a45ca1-125f-49ac-9c5f-8fd4fcc2bd9d
    type: content
  - name: iTunes
    id: e4a87322-13e7-492e-a732-bba9088b1feb
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: PAT KAYE
description: LACK OF BUDGET
