typography_spectrum: 0.5598632437177002
color:
  saturation: 0.6540196472778916
  brandStrength: 0.44376980303786695
  lightness: 0.07657347363419831
  brandColors:
    - '#081D6A'
    - '#D2001A'
    - '#FFDC00'
    - '#F8AC00'
    - '#172863'
  rhythmicContrast: 0.7665214303415269
layout_spectrum: 0.5954750839155167
name: PAT-K
navigation:
  - name: iTunes
    id: e4a87322-13e7-492e-a732-bba9088b1feb
    type: content
  - name: Contact
    id: 1dbd0afe-a0f8-4078-9d42-a48cb94750f8
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: PAT KAYE
description: LACK OF BUDGET
