typography_spectrum: 0.4106741009745747
color:
  saturation: 0.030459574656561017
  brandStrength: 0.36585721117444336
  rhythmicContrast: 0.21219354798085988
  brandColors:
    - '#081D6A'
    - '#D2001A'
    - '#FFDC00'
    - '#F8AC00'
    - '#172863'
  lightness: 0.2933998361695558
layout_spectrum: 0.6173323527909815
name: PAT-K
navigation:
  - name: PAT-K
    url: 'https://www.youtube.com/channel/UCOOB2omxQavA0g-tZcXgTSw'
    type: external
  - name: iTunes
    url: 'https://itunes.apple.com/us/album/lack-of-budget/id1142079201'
    type: external
  - name: Tidal
    url: 'https://listen.tidal.com/album/63795602'
    type: external
  - name: Spotify
    url: 'https://play.spotify.com/album/0Bp5hphrYFHPvaxxsWPpBk'
    type: external
  - name: Amazon
    url: >-
      https://www.amazon.com/s/ref=ntt_srch_drd_B01K1DV478?ie=UTF8&field-keywords=Pat%20Kaye&index=digital-music&search-type=ss
    type: external
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: PAT-K
description: LACK OF BUDGET
