typography_spectrum: 0.9453745181672275
color:
  saturation: 0.6540196472778916
  brandStrength: 0.443769803037867
  rhythmicContrast: 0.7665214303415269
  brandColors:
    - '#081D6A'
    - '#D2001A'
    - '#FFDC00'
    - '#F8AC00'
    - '#172863'
  lightness: 0.07657347363419831
layout_spectrum: 1
name: PAT-K
navigation:
  - name: Contact
    id: 6ff571be-15de-4922-ab76-be6553c8b2d6
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: PAT KAYE
description: LACK OF BUDGET
