typography_spectrum: 0.4421777883544564
color:
  saturation: 0.025348129216581583
  brandStrength: 0.37945388606749475
  lightness: 0.43039234168827534
  brandColors:
    - '#081D6A'
    - '#D2001A'
    - '#FFDC00'
    - '#F8AC00'
    - '#172863'
  rhythmicContrast: 0.08603375568054616
layout_spectrum: 0.34232451650314033
name: PAT-K
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: PAT KAYE
description: LACK OF BUDGET
