typography_spectrum: 0.2496010595932603
color:
  saturation: 0.038564326940104365
  brandStrength: 0.313209485495463
  lightness: 0.09900227631442249
  brandColors:
    - '#081D6A'
    - '#D2001A'
    - '#FFDC00'
    - '#F8AC00'
    - '#172863'
  rhythmicContrast: 0.24528868775814772
layout_spectrum: 0.34232451650314033
name: PAT-K
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: PAT KAYE
description: LACK OF BUDGET
