typography_spectrum: 0.9783241045661271
color:
  saturation: 0.5096053252927959
  brandStrength: 0.15438150288537145
  lightness: 0.6173969449009746
  brandColors:
    - '#A40000'
    - '#010001'
    - '#FFFEFF'
    - '#A8A7A8'
    - '#C65F5F'
  rhythmicContrast: 0.21779201459139585
layout_spectrum: 0.34232451650314033
name: PAT-K
navigation:
  - name: iTunes
    id: e4a87322-13e7-492e-a732-bba9088b1feb
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: PAT KAYE
description: LACK OF BUDGET
