typography_spectrum: 0.15209103818051517
color:
  saturation: 0.6540196472778916
  brandStrength: 0.443769803037867
  rhythmicContrast: 0.7665214303415269
  brandColors:
    - '#081D6A'
    - '#D2001A'
    - '#FFDC00'
    - '#F8AC00'
    - '#172863'
  lightness: 0.07657347363419831
layout_spectrum: 1
name: PAT-K
navigation:
  - name: Spotify
    url: 'https://play.spotify.com/album/0Bp5hphrYFHPvaxxsWPpBk'
    type: external
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: PAT KAYE
description: LACK OF BUDGET
