typography_spectrum: 0.3859932217746973
color:
  saturation: 0.3529444320593029
  brandStrength: 0.09618159290403128
  lightness: 0.11533760651946068
  brandColors:
    - '#DDDCC5'
    - '#958976'
    - '#611427'
    - '#1D2326'
    - '#6A6A61'
  rhythmicContrast: 0.46404961682856083
layout_spectrum: 0.5842733501922339
name: PAT-K
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: PAT KAYE
description: LACK OF BUDGET
